version: "3.9"

services:
  postgres_db:
    env_file: .env
    image: postgres:14.6-alpine3.16
    ports:
      - "${PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"